page Home
  Container max: "xl"
    Copy tone: "muted" -> "Axonix Site Template"
    Card title: "{{APP_NAME}}"
      Copy -> "A presentation-first Axonix starter for shipping landing pages, product stories, and launch surfaces."
    Grid cols: 3, gap: "lg"
      Card title: "Single Binary"
        Copy -> "Keep the runtime story tight and Rust-first."
      Card title: "Algebraic UI"
        Copy -> "Author screens in Axonix-first building blocks."
      Card title: "Runtime Ready"
        Copy -> "Switch between path, git, and future registry runtime flows."
