page DocsHome
  Container max: "xl"
    Grid cols: 3, gap: "lg"
      Card title: "Getting Started"
        Copy -> "Explain install, scaffold, runtime sources, and the first Axonyx page loop."
        a href: "/getting-started" -> "Open section"
      Card title: "Reference"
        Copy -> "Document components, layout rules, metadata directives, and runtime behavior."
        a href: "/reference" -> "Open section"
      Card title: "Examples"
        Copy -> "Collect small complete examples that show how Axonyx should feel in practice."
        a href: "/examples" -> "Open section"
