page Home
  Container max: "xl", recipe: "hello-shell"
    Card title: "Hello Axonyx", recipe: "hero-card"
      Copy tone: "eyebrow" -> "{{APP_NAME}}"
      Copy tone: "lead" -> "Start with one clean .ax page, keep JavaScript small, and let Rust stay underneath the framework."
      Button tone: "primary" -> "Edit app/page.ax"
    Grid cols: 3, gap: "md"
      Card title: "Write in .ax"
        Copy -> "Keep pages readable with indentation-first authoring instead of JSX-heavy boilerplate."
      Card title: "Lower into Rust"
        Copy -> "Axonyx stays framework-shaped on top while Rust remains the execution engine below."
      Card title: "Grow from here"
        Copy -> "Use app/posts, routes/api, and jobs as the next slice once this hello page feels right."
